#!/bin/bash

cecho() {
	type lolcat >/dev/null && {
		echo -e "$@" | lolcat
	} || {
		echo -e "\x1b[31m$@\x1b[0m"
	}
}

usage() {
	echo qroc - send files a with QR code convenience
	printf '\tUsage: ' ; cecho 'qroc file_to_send'
	echo -e '\tThen open a QR scanner on your phone and copy the text of the QR code.'
	echo -e '\tFinally, open croc on your phone - the code is in your clipboard!'
}

[[ $# = 1 ]] || {
	usage
	exit 1
}

code=`mktemp -u XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`

qrencode -t utf8 "$code"
croc send --code "$code" "$1"
